version: "3.9"

services:
  torproxy:
    image: dperson/torproxy:aarch64
    # build:
    #   context: https://github.com/dperson/torproxy.git
    #   dockerfile: Dockerfile.aarch64
    expose:
      - "8118"
      - "9050"
      - "9051"
    # ports:
    #   - "8118:8118"
    #   - "9050:9050"
    #   - "9051:9051"
    environment:
    - BW=1000
    - TZ=Asia/Tokyo
    - PASSWORD=${TOR_PASSWORD}
    restart: unless-stopped
  packager:
    image: arm64v8/python:${PYTHON_VERSION}-slim
    volumes:
      - python_packages:/usr/local/lib/python${PYTHON_VERSION}/dist-packages
    command: pip3 install ${PYTHON_PACKAGES}
  scrapyd:
    build:
      context: 'https://github.com/EasyPi/docker-scrapyd.git'
      # context: 'https://github.com/vimagick/dockerfiles.git#:scrapyd'
      dockerfile: Dockerfile
    ports:
      - "6800:6800"
    volumes:
      - scrapyd_data:/var/lib/scrapyd
      - python_packages:/usr/local/lib/python${PYTHON_VERSION}/dist-packages
      - ./scrapyd.conf:/etc/scrapyd/scrapyd.conf:ro
    restart: unless-stopped
    environment:
    - TZ=Asia/Tokyo
#  scrapyrt:
#    build:
#      context: https://github.com/EasyPi/docker-scrapyd.git
#      dockerfile: Dockerfile
#    command: scrapyrt -i 0.0.0.0 -p 9080
#    ports:
#      - "9080:9080"
#    restart: unless-stopped

volumes:
  python_packages:
  scrapyd_data:
