version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - TZ=${POSTGRES_TZ}
      - PGTZ=${POSTGRES_TZ}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
